name: 02 - Workflows Events
on:
    push:
    pull_request:
    schedule: 
        - cron: "30 5 * * 1,3"
    workflow_dispatch:

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Show the trigger
        run: echo "Push Event"
