name: 07 - Using Expressions

on: 
    push:
    workflow_dispatch:
        inputs:
            debug:
                type: boolean
                default: false

run-name: 07 - Using Expressions | DEBUG - ${{ inputs.debug && 'ON' || 'OFF' }}

jobs:
  echo:
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        if: ${{ inputs.debug }} == 'true'
        run: |
            echo "Event Name: ${{ github.event_name }}"
            echo "Branch: ${{ github.ref }}"
            echo "Commit SHA: ${{ github.SHA }}"
            echo "Runner OS: ${{ runner.os }}"
      - name: Print when triggered from main
        if: ${{ inputs.debug }} == 'true' && ${{ github.ref }} == 'refs/heads/main'
        run: echo "I was triggered from main"
      - name: Greeting
        run: echo "Hello, world"


                    
