name: 07 - Using Variables

on: 
    push:
    workflow_dispatch:

env:  
        WORKFLOW_VAR: 'I am a workflow env var' 
        OVERWRITTEN: 'I`ll me overwritten'

jobs:
  echo:
    env: 
     JOB_VAR: 'I am job env var'
     OVERWRITTEN: 'I have been overwritten at the job level'
    runs-on: ubuntu-latest
    steps:
      - name: Display Information
        env:
         STEP_VAR: 'I am a step env var'
         step_var2: 'I am another step var'
        run: |
         echo "Step env var: ${{ env.STEP_VAR }}"
         echo "Step env var 2: ${{ env.step_var2 }}"
         echo "Job env var: ${{ env.JOB_VAR }}"
         echo "Workflow env var: ${{ env.WORKFLOW_VAR }}"
         echo "Overwritten: ${{ env.STEP_VAR }}"
      - name: Overwrite Job Variable
        env:
         OVERWRITTEN: 'I have been overwritten at the step level'
        run: echo "hi"




                    
