name: 11 - Working with Inputs
on: 
    workflow_dispatch:
        inputs:
            dry-run:
                description: "Skip deployment and only print build output"
                type: boolean
                default: false
            target:
                description: "Which environment the workflow will target"
                type: environment
                required: false
            tag:
                description: "Release from which to build and deploy"
                type: choice
                default: v3
                options:
                    - v1
                    - v2
                    - v3        

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Build
              run: echo "Building from tag <retrieve the value of the tag input here>"
    deploy:
        runs-on: ubuntu-latest
        needs: 
            - build
        if: ${{ !inputs.dry-run }}
        environment: ${{ inputs.target }}
        steps:
            - name: Deploy
              run: echo "Deploying to ${{ inputs.target }}"


